CI workflow
devflowinc/firecrawl-simple pull request #15
Opened 2024-11-06 00:48 UTC by daveads

add automated Docker image builds for PRs

- Add API service Docker build workflow
- Add Puppeteer service Docker build workflow
- Configure Docker Hub authentication

/claim #14

2024-11-06 00:48 UTC, daveads commented
Test... 

https://github.com/daveads/firecrawl-simple/actions/runs/11694973052/job/32569604382

2024-11-06 00:49 UTC, daveads commented
Remember to add this secrets 

secrets.DOCKER_USERNAME
secrets.DOCKER_PASSWORD

2024-11-06 00:57 UTC, daveads commented
removed pushing to docker...

2024-11-06 01:07 UTC, daveads commented
@skeptrunedev done with this.

2024-11-11 23:14 UTC, cdxker requested changes
Can you change the tags to be trieve/firecrawl and puppeteer-service-ts

2024-11-11 23:14 UTC, cdxker commented on .github/workflows/build-docker-images.yml
> +          tags: firecrawl:pr-${{ github.event.number }}
```suggestion
          tags: trieve/firecrawl:pr-${{ github.event.number }}
```

2024-11-11 23:14 UTC, cdxker commented on .github/workflows/build-docker-images.yml
> +          tags: puppeteer-service-ts:pr-${{ github.event.number }}
```suggestion
          tags: trieve/puppeteer-service-ts:pr-${{ github.event.number }}
```

2024-11-12 06:19 UTC, daveads commented on .github/workflows/build-docker-images.yml
> +          tags: puppeteer-service-ts:pr-${{ github.event.number }}
sure...

2024-11-12 09:31 UTC, daveads commented
@cdxker  done

2024-11-22 07:52 UTC, cdxker approved these changes

2024-11-22 08:03 UTC, merged